name: Build Docker Image
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: 
      - self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

            
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          push: false
          tags: your-username/your-repo:latest
